### ISSUE TITLE
NPE when regexIgnored isn't included

### ISSUE THREAD

**Issue by chege** [jdcasey/enforce-managed-deps-rule#5]
A NPE is thrown when regexIgnored is not set:
```
Caused by: java.lang.NullPointerException
	at org.commonjava.maven.enforcer.rule.EnforceManagedDepsRule.checkRegex(EnforceManagedDepsRule.java:119)
	at org.commonjava.maven.enforcer.rule.EnforceManagedDepsRule.check(EnforceManagedDepsRule.java:107)
	at org.commonjava.maven.enforcer.rule.EnforceManagedDepsRule.execute(EnforceManagedDepsRule.java:44)
	at org.apache.maven.plugins.enforcer.EnforceMojo.execute(EnforceMojo.java:193)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	... 20 more
```
(sorry for reopening/closing/reopening...small touchpad related problem)

**Comment by jdcasey** [comment]
Fixed in #6
